version: '3.8'
services:
    web:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 80:80
        networks:
          - mysql_network
        # networks:
        #   - mynetwork
    db:
        container_name: db
        # image: mysql
        build:
            context: ./mysql
            dockerfile: Dockerfile
        volumes:
            - ./mysql/config:/etc/mysql/conf.d/source
            - db:/var/lib/mysql
            - ./mysql/scripts:/docker-entrypoint-initdb.d
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: mysql@123
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: mysql_user
            MYSQL_PASSWORD: er$$786op
        ports:
            - "3306:3306"
        networks:
            - mysql_network
        # networks:
        #   - mynetwork
        #   - mysqlnetfpm
    postgres:
        container_name: postgres
        build:
            context: ./postgres
            dockerfile: Dockerfile    
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: postgres@123
            POSTGRES_DB: postgres
        ports:
        - "5432:5432"
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        networks:
            - mysql_network            
    # phpmyadmin:
    #   image: phpmyadmin/phpmyadmin
    #   ports:
    #       - '81:80'
    #   restart: always
    #   environment:
    #       PMA_HOST: db
    #   depends_on:
    #       - db
volumes:
    db:
networks:
 mysql_network:        
    name: mynetwork
    external: true           
# networks:
#     mynetwork
#   mysqlnet:
#     driver: bridge
#   mysqlnetfpm:
#     driver: bridge