version: '3.8'
services:
    web:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 80:80
        networks:
          - mysql_network
    db:
        container_name: db
        image: mysql:8.0.20  # Use a compatible MySQL version
        volumes:
            - ./mysql/config:/etc/mysql/conf.d/source
            - ./mysql/data:/var/lib/mysql
            - ./mysql/scripts:/docker-entrypoint-initdb.d
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "mysql@123"
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: mysql_user
            MYSQL_PASSWORD: er$$786op
        ports:
            - "3306:3306"
        networks:
            - mysql_network
    postgres:
        container_name: postgres
        build:
            context: ./postgres
            dockerfile: Dockerfile    
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: postgres@123
            POSTGRES_DB: postgres_db  # Change to match Dockerfile
        ports:
        - "5432:5432"
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        networks:
            - mysql_network
volumes:
    db:
networks:
    mysql_network:
        name: mynetwork
        external: true